apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-api-blue # Consider ${COLOR }
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-api-blue # Consider ${COLOR }
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70