apiVersion: v1
clusters:
  - cluster:
      server: ${EKS_ENDPOINT}
      certificate-authority-data: ${EKS_CA_CERT}
    name: eks-cluster
contexts:
  - context:
      cluster: eks-cluster
      user: aws
    name: eks-context
current-context: eks-context
users:
  - name: aws
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: aws
        args:
          - eks
          - get-token
          - --cluster-name
          - ${EKS_CLUSTER_NAME}
          - --region
          - ${AWS_REGION}